apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cart-page-rs
  namespace: prerana-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      web: cart
  template: # it determines which application we want to deploy
    metadata:
      labels:
        web: cart
    spec: #it  defines behaviour of pod and container
      containers:
        - name: cart-container
          image: muralisocial123/cart-page-test:1.0
          ports:
            - containerPort: 3000
